# Generated by Django 4.1.7 on 2023-04-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilitypoll',
            name='duration',
            field=models.TimeField(),
        ),
    ]
