# Generated by Django 4.1.7 on 2023-04-14 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_alter_availabilitypoll_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitypoll',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
