# Generated by Django 4.1.7 on 2023-04-16 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_merge_20230414_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilitypoll',
            name='datetime_ranges',
        ),
        migrations.AddField(
            model_name='availabilitypoll',
            name='defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datetimerange',
            name='matrix',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datetimerange',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.availabilitypoll'),
            preserve_default=False,
        ),
    ]
