# Generated by Django 4.2.1 on 2023-05-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_pollanswer_justification_pollanswer_poll_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollanswer',
            old_name='avaliable',
            new_name='available',
        ),
    ]
