# Generated by Django 4.1.7 on 2023-04-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='group_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='orginvitation',
            old_name='acptance',
            new_name='accepted',
        ),
        migrations.RenameField(
            model_name='orginvitation',
            old_name='group_01',
            new_name='group',
        ),
        migrations.RemoveField(
            model_name='orginvitation',
            name='message',
        ),
    ]
