# Generated by Django 4.1.7 on 2023-04-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_remove_orginvitation_email_orginvitation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orginvitation',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
