# Generated by Django 4.1.7 on 2023-04-13 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0003_participant_alter_availabilitypoll_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilitypoll',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
