# Generated by Django 4.1.7 on 2023-04-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_availabilitypoll_participants_and_more'),
        ('polls', '0005_availabilitypoll_admins'),
    ]

    operations = [
    ]
