# Generated by Django 4.2.1 on 2023-06-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_pollanswer_matrix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetimerange',
            name='matrix',
            field=models.CharField(max_length=255),
        ),
    ]
